name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar SSH
        run: |
          set -e
          set -x
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY_2 }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 186.250.185.26 >> ~/.ssh/known_hosts

      - name: Conectar ao servidor e executar comandos de deploy
        run: |
          ssh root@186.250.185.26 '
            cd /prismafive/projetos/samplefrontend &&
            git pull origin main &&
            docker compose build &&
            docker compose up -d
          '